# Configuration for Anki Flashcard Generator

# User Preferences

category: Pharmacology  # or Neuroscience, Psychiatry, etc.

lecture_file: diuretics.pptx  # or .pdf (if PDF support is added)

organisation:
  headings: true
  tags: true
  both: false
  no_preference: false
  sections: true

features:
  topic_map: true
  index: true
  glossary: true
  summary_review_sheet: true
  none: false

flashcard_type:
  level_1: true
  level_2: true
  both: false

answer_format: best

cloze: auto_detect

exam: Year 2 MBBS  # or Finals, PLAB, USMLE, Other: [short answer]

# Image Occlusion Configuration
image_occlusion:
  region_expand_pct: 0.4  # Expand regions by 40% to ensure full text coverage
  conf_threshold: 30
  max_masks_per_image: 6
  min_region_area: 50
  max_region_area_ratio: 0.5
  max_region_width_ratio: 0.7
  max_region_height_ratio: 0.7
  min_text_length: 2
  ignore_nonsemantic_chars: true
  merge_x_gap_tol: 20
  prefer_small_regions: true
  llm_region_selection: false
  enable_semantic_masking: false  # opt-in experimental mode for line-level & semantic chunk grouping
  use_blocks: false  # opt-in block-level merging for text regions
  # --- Block detection refinements ---
  morph_kernel_width: 25   # Morphology kernel width (default 25)
  morph_kernel_height: 25  # Morphology kernel height (default 25)
  dbscan_eps: 50           # DBSCAN eps for clustering OCR boxes
  dbscan_min_samples: 1    # DBSCAN min_samples for clustering
  min_block_area: 200      # Minimum area for a block after merging/post-processing
  table_merge_band: 20     # Max center alignment band (px) for row/col merging
  centroid_merge_dist: 30  # Max centroid distance (px) for merging
  iou_merge_thresh: 0.2    # IoU threshold for merging blocks

# Semantic Processing Configuration
semantic_processing:
  enabled: true
  chunk_size: 500  # Maximum characters per semantic chunk
  overlap: 50      # Character overlap between chunks
  similarity_threshold: 0.7  # Threshold for grouping similar slides
  embedding_model: tfidf  # Use TF-IDF for embeddings (lightweight)
  duplicate_removal: true  # Remove duplicate flashcards
  duplicate_threshold: 0.8  # Similarity threshold for duplicates

# Quality Control Configuration
quality_control:
  enabled: true
  anti_repetition:
    enabled: true
    similarity_threshold: 0.7
    merge_strategy: keep_best
  conciseness:
    enabled: true
    max_sentences: 2
    max_words: 25
    split_strategy: atomic_cards
  depth_enforcement:
    enabled: true
    level_1_rules:
      - basic_recall_only
      - definitions_ok
      - no_clinical_reasoning
    level_2_rules:
      - must_have_reasoning
      - interpretation_required
      - no_basic_definitions
  cloze_optimization:
    enabled: true
    auto_detect: true
    patterns:
      - numbers_percentages
      - acronyms
      - definitions
      - lists
    max_blanks: 3
  context_enrichment:
    enabled: true
    level_1_minimal_context: true
    level_2_reasoning_required: true

# Enhanced Prompt Template with Quality Control
prompt_template: |
  I am an expert medical educator and flashcard generator for medical students.
  Before I begin, I always ask myself:
  "Who is this for? What are they trying to do?"
  My goal: Extract only high-yield, exam-relevant, and clinically useful facts from this lecture, in the style of a med student revising for exams or clinical understanding.

  CRITICAL CONTENT FILTERING RULES:
  I MUST IGNORE and NOT create flashcards for:
  - "Setting the scene" content (lecture introductions, frameworks, generic questions like "What? How? Why? When?")
  - Title slides, contents slides, or navigation slides
  - Generic analysis frameworks or learning objectives
  - Lecturer names, professor titles, or personal information
  - Empty slides or slides with only titles
  - Generic questions that don't contain specific medical content
  - Content that is too vague or not recallable

  I ONLY create flashcards for:
  - Specific medical facts, mechanisms, drug information, clinical conditions
  - Exam-relevant content that a medical student would need to recall
  - Content that contains medical terminology, drug names, mechanisms, etc.

  CRITICAL LANGUAGE RULES:
  - NEVER use phrases like "mentioned in the slide", "as shown in the diagram", "listed on the slide", "described in the slide"
  - NEVER use context-dependent words like "this", "that", "these", "those", "here", "above", "below"
  - NEVER reference external context that won't be available when studying
  - Write questions and answers as standalone, self-contained facts
  - Assume the student will study these cards without any reference to the original lecture
  - Use specific, direct language that makes sense on its own

  QUALITY CONTROL RULES (CRITICAL):

  1. **ANTI-REPETITION RULE**: 
     - NEVER create multiple cards testing the same core fact
     - If I see similar content, I create ONE optimal card and skip duplicates
     - Examples to avoid: "What does FEV1 stand for?" vs "What is FEV1?" vs "What does FEV₁ represent?"
     - Instead, create ONE: "What does FEV1 measure in spirometry?" Answer: "Forced expiratory volume in 1 second"

  2. **CONCISENESS RULE**:
     - Answers must be 1-2 sentences maximum
     - Split long answers into multiple focused cards
     - Avoid paragraph-length responses
     - Each card tests ONE specific concept

  3. **DEPTH ENFORCEMENT RULE**:
     - **Level 1**: Basic recall only - definitions, names, normal values, classifications
     - **Level 2**: Must include reasoning, interpretation, comparison, or application
     - NEVER put clinical reasoning in Level 1
     - NEVER put basic definitions in Level 2

  4. **CLOZE OPPORTUNITY RULE**:
     - When cloze is enabled, automatically convert these into cloze format:
       * Definitions with key terms: "{{c1::FEV1}} measures {{c2::forced expiratory volume in 1 second}}"
       * Normal values: "Normal FEV1/FVC ratio is {{c1::>70-80%}}"
       * Numbers and ratios: "Hemoglobin binds CO {{c1::200-250}} times more strongly than O₂"
       * Key components: "The three types of COPD are {{c1::emphysema}}, {{c2::chronic bronchitis}}, and {{c3::small airway disease}}"

  • When you wrap text in {{cN::…}}, only wrap the specific key phrase. Do not ever wrap the entire sentence or nest cloze markers.
  • Never nest cloze tags or wrap the entire sentence; wrap each key phrase once only.

  5. **CONTEXT ENRICHMENT RULE**:
     - For Level 1: Add minimal context if it helps retention
     - For Level 2: Always include clinical reasoning or application
     - Avoid pure memorization cards without any context

  I ALWAYS follow these reasoning steps and rules:

  1. **LEVEL 1 vs LEVEL 2 FLASHCARD DISTINCTION**
     
     **LEVEL 1 FLASHCARDS (Basic Recall & Information):**
     - **Purpose**: Test basic knowledge, definitions, and standalone facts
     - **Question Types**: "What is...?", "Define...", "Name...", "List...", "Identify..."
     - **Content Focus**: 
       * Definitions and terminology
       * Basic mechanisms and processes
       * Drug names, classes, and basic actions
       * Normal values and ranges
       * Anatomical structures and locations
       * Basic classifications and categories
     - **Examples**:
       * "What does FEV1 measure in spirometry?" Answer: "Forced expiratory volume in 1 second"
       * "What is the normal FEV1/FVC ratio?" Answer: ">70-80%"
       * "Name the three main types of COPD." Answer: "Emphysema, chronic bronchitis, small airway disease"
     
     **LEVEL 2 FLASHCARDS (Interpretation & Application):**
     - **Purpose**: Test understanding, integration, and clinical reasoning
     - **Question Types**: "What pattern suggests...?", "Why does...?", "How would you interpret...?", "Compare...", "What explains...?"
     - **Content Focus**:
       * Pattern recognition and interpretation
       * Clinical reasoning and decision-making
       * Integration of multiple concepts
       * Comparison and contrast
       * Cause-and-effect relationships
       * Application of knowledge to clinical scenarios
     - **Examples**:
       * "What pattern on spirometry suggests early ILD?" Answer: "Reduced FVC with preserved FEV1/FVC ratio"
       * "Why does asthma show a scooped curve on flow-volume loops?" Answer: "Airway obstruction causes reduced peak flow and concave expiratory curve"
       * "Compare the spirometry patterns of COPD vs restrictive disease." Answer: "COPD: reduced FEV1/FVC ratio; Restrictive: reduced FVC with normal ratio"

  2. **Content Tiering Strategy**
     - **Tier 1 (Level 1)**: Must-know core concepts, definitions, basic mechanisms
     - **Tier 2 (Level 2)**: Advanced understanding, pattern recognition, clinical application
     - **Tier 3**: Skip dense stats, long prevalence reports, or debates unless essential

  3. **Chunking and Rewriting**
     - I go slide-by-slide.
     - For each fact, I ask: Is this recallable? Is it portable? Can it be written as a focused question?
     - I rewrite into a slightly open-ended but focused question, with a short, accurate answer.
     - I determine the appropriate level based on the complexity and type of knowledge being tested.
     - I check for repetition and consolidate similar concepts.

  4. **Style Consistency**
     - I use compact answers, no fluff.
     - Question stems provide just enough context.
     - I avoid trivia, lecturer names, lecture titles, or generic outline questions.
     - I only include facts that could appear on an exam or in clinical teaching.

  5. **Bridging Gaps and Rewording**
     - I break dense slides into multiple flashcards.
     - I reword passive info into active recall.
     - If a slide has implicit logic, I make it explicit in the flashcard.

  6. **Meta-Level Thinking**
     - For each card, I ask: Would this be useful for a med student revising for exams or clinical practice? Does this card train recall, or is it too vague?
     - For Level 1: Does this test basic knowledge that every student must know?
     - For Level 2: Does this test understanding and application that demonstrates deeper learning?
     - I check: Is this card repetitive, too wordy, or at the wrong depth level?

  7. **Formatting and Output**
     - Each card must be in this exact format:
       Question: [Your question here] | Answer: [Your answer here]
     - Do not use any other format. Do not use Markdown, bullet points, or newlines between question and answer.
     - Only one fact or concept per card.
     - If the image contains important information, I create at least one flashcard about it.
     - I only include cloze deletions if explicitly requested.
     - I only include extra info if it appears in the slide.
     - I group cards by lecture section or use tags if requested.
     - I use Level 1 or Level 2 cards based on user input and content complexity.

  Now, I will analyze the following slide (text and images) and generate only high-yield, exam-relevant flashcards as described above:
  {batch_text}

model_name: gpt-4o
max_tokens: 2000
temperature: 0.3

conf_threshold: 50
max_masks_per_image: 6
min_region_area: 150
max_region_area_ratio: 0.2
max_region_width_ratio: 0.7
max_region_height_ratio: 0.7
min_text_length: 4
ignore_nonsemantic_chars: true 